version: "3"
name: stackoverflow-services
services:
  mysql:
    image: mysql:latest
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: "stackoverflow_api_db"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - main_network
  api:
    container_name: backend_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      DB_HOST: mysql
    depends_on:
      - mysql
    command: yarn run dev
    networks:
      - main_network
  adminer:
    container_name: database_manager
    image: adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    networks:
      - main_network
volumes:
  mysql-data:
networks:
  main_network:
    driver: bridge
