version: "3"
name: stackoverflow-api
services:
  database:
    image: mysql:latest
    container_name: database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stackoverflow_api_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - main_network
  api:
    container_name: backend_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      env_file: ".env"
    depends_on:
      - database
    command: yarn run dev
    networks:
      - main_network
volumes:
  mysql-data:
networks:
  main_network:
    driver: bridge
